version: "3.7"

services:

    flask:
      build: ./flask-app
      container_name: flask_app
      restart: always
      expose:
         - 5000

    nginx:
      build: ./nginx-flask
      container_name: nginx-flask
      restart: always
      ports:
         - "80:80"
      depends_on:
         - "flask"

    frontend:
      build: ./react-frontend
      container_name: react_frontend
      restart: always
      expose:
         -  3000
      depends_on:
         - "flask"
