version: "3.7"

services:

        flask:
                image: giljaniz/api_flask:v1
                container_name: flask_app
                restart: always
                expose:
                     - 5000

        nginx:
                image: giljaniz/api_nginx:v1
                container_name: nginx-flask
                restart: always
                ports:
                        - "80:80"
                depends_on:
                        - "flask"

        frontend:
                image: giljaniz/api_frontend:v1
                container_name: react_frontend
                restart: always
                expose:
                    - 3000
                depends_on:
                    - "flask"